version: '3.8'

services:
  ostraka-service:
    build:
      context: docker/dev
    container_name: ostraka-service
    volumes:
      - .:/service
    working_dir: /service
    ports:
      - "4000:4000"
    env_file:
      - .env